travel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("yatra.urls"))
]
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yatra/urls.py
from django.urls import path
from .views import*

app_name="yatra"

urlpatterns = [
	path('', Home.as_view(), name="home"),
	path('contact/', ContactView.as_view(), name="contact"),
	path('galery/', GaleryView.as_view(), name="galery"),
]

yatra/models.py
from django.db import models

# Create your models here.


class Destination(models.Model):
    name = models.CharField(max_length=200)
    images = models.ImageField(upload_to='destination')
    descriptions = models.TextField()
    cost = models.DecimalField(max_digits=20, decimal_places=3)
    country = models.CharField(max_length=200)

    def __str__(self):
        return self.name

yatra/views.py
from django.shortcuts import render
from django.views.generic import*
from .models import*
# Create your views here.


class Home(TemplateView):
    template_name = "home.html"

    def get_context_data(self,**kwrags):
    	context=super().get_context_data(**kwrags)
    	context['yatra']=Destination.objects.all()

    	return context


class ContactView(TemplateView):
    template_name = "contact.html"


class GaleryView(TemplateView):
    template_name = "galery.html"

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
	<title>Wander Travel Category Bootstrap Responsive Website Template | Home :: W3layouts</title>
	<!-- Meta tag Keywords -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta charset="UTF-8" />
	<meta name="keywords" content="Wander Responsive web template, Bootstrap Web Templates, Flat Web Templates, Android Compatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyEricsson, Motorola web design" />
	<script>
		addEventListener("load", function () {
			setTimeout(hideURLbar, 0);
		}, false);

		function hideURLbar() {
			window.scrollTo(0, 1);
		}
	</script>
	<!--// Meta tag Keywords -->

	<!-- Custom-Files -->
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<!-- Bootstrap-Core-CSS -->
	<link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" media="all" />
	<!-- Style-CSS -->
	<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
	<!-- Font-Awesome-Icons-CSS -->
	<!-- //Custom-Files -->

	<!-- Web-Fonts -->
	<link href="//fonts.googleapis.com/css?family=Aleo:300,300i,400,400i,700,700i&amp;subset=latin-ext" rel="stylesheet">
	<link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese"
	 rel="stylesheet">
	<!-- //Web-Fonts -->
</head>

<body>
	<div id="home">
		<!-- banner -->
        <!-- //banner -->
          		{% block banner %}
  
          		{% endblock %}
    </div>
          		{% block content %}

          		{% endblock %}

	
	
	<footer class="py-4">
		<div class="container py-xl-5 py-3">
			<div class="row">
				<div class="col-lg-4 col-sm-6 col-8 footer-grid">
					<h2 class="mb-3">
						<a class="logo-footer tm-clr let" href="index.html">Wander</a>
					</h2>
					<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremqu.</p>
				</div>
				<div class="offset-lg-1 col-lg-2 col-sm-6 col-4 footer-grid mt-lg-0 mt-4">
					<ul class="list-unstyled">
						<li>
							<a href="index.html">Index</a>
						</li>
						<li class="my-2">
							<a href="#about">About Us</a>
						</li>
						<li>
							<a href="#what">What We Do</a>
						</li>
					</ul>
				</div>
				<div class="col-lg-2 col-6 footer-grid mt-lg-0 mt-4">
					<ul class="list-unstyled">
						<li>
							<a href="#desti">Destination</a>
						</li>
						<li class="my-2">
							<a href="#blog">Blog</a>
						</li>
						<li>
							<a href="single.html">Blog Details</a>
						</li>
					</ul>
				</div>
				<div class="col-lg-2 col-6 footer-grid mt-lg-0 mt-4">
					<ul class="list-unstyled">
						<li>
							<a href="gallery.html">Gallery</a>
						</li>
						<li class="my-2">
							<a href="contact.html">Contact Us</a>
						</li>
						<li>
							<a href="#some">Some More</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</footer>
	<!-- //footer -->

	<!-- footer social icons -->
	<div class="social-icons-footer text-center my-3">
		<ul class="list-unstyled">
			<li>
				<a href="#">
					<span class="fa fa-facebook"></span>
				</a>
			</li>
			<li>
				<a href="#">
					<span class="fa fa-twitter"></span>
				</a>
			</li>
			<li>
				<a href="#">
					<span class="fa fa-google-plus"></span>
				</a>
			</li>
			<li>
				<a href="#">
					<span class="fa fa-instagram"></span>
				</a>
			</li>
		</ul>
	</div>
	<!-- //footer social icons -->
	<!-- copyright -->
	<div class="copy_right mb-5">
		<p class="text-center text-bl let">© 2019 Wander. All rights reserved | Design by
			<a href="http://w3layouts.com/">Robin Rai</a>
		</p>
	</div>
	<!-- //copyright -->

	<!-- move top icon -->
	<a href="#home" class="move-top text-center"></a>
	<!-- //move top icon -->

templates/contact.html
{% extends "base.html" %}
{% load static %}
<!--{% block abc%}main-banner-2{% endblock %} -->

{% block content %}

<div id="home">
	<!-- banner -->
	<div class="banner_w3lspvt-4">
		<!-- nav -->
		<div class="nav_w3ls pt-4 pb-3 text-center">
			<nav>
				<label for="drop" class="toggle">Menu</label>
				<input type="checkbox" id="drop" />
				<ul class="menu">
					<li><a href="{% url 'yatra:home' %}">Home</a></li>
					<li><a href="index.html">Destination</a></li>
					<li>
						<!-- First Tier Drop Down -->
						<label for="drop-2" class="toggle toogle-2">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
						</label>
						<a href="#">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span></a>
						<input type="checkbox" id="drop-2" />
						<ul class="text-left">
							<li><a href="index.html" class="drop-text">About Us</a></li>
							<li><a href="index.html" class="drop-text">What We Do?</a></li>
							<li><a href="index.html" class="drop-text">Blog</a></li>
							<li><a href="single.html" class="drop-text">Blog Details</a></li>
						</ul>
					</li>
					<li><a href="{% url 'yatra:galery' %}">Gallery</a></li>
					<li><a href="{% url 'yatra:contact' %}" class="active">Contact Us</a></li>
				</ul>
			</nav>
		</div>
		<!-- //nav -->
		<div class="banner-text-2 text-right">
			<div class="banner-bot-2">
				<h1><a href="index.html" class="logo text-wh editContent">Wander</a></h1>
			</div>
		</div>
	</div>
	<!-- //banner -->
</div>

<!-- contact -->
<div class="contact-w3l py-5">
	<div class="container py-xl-5 py-lg-3">
		<div class="text-center mb-sm-5 mb-4 pb-lg-4">
			<h3 class="tittle text-bl let">Contact Us</h3>
		</div>
		<div class="row">
			<div class="col-lg-6 contact-w3pvt-mobiits-w3layouts">
				<h4 class="contact-title text-bl mb-4">Our Address</h4>
				<h5 class="font-weight-light text-bl">If you have any questions about the services we provide simply use the
					form below. We try and respond to all queries
					and comments within 24 hours.</h5>
				<div class="midd-contact my-xl-5 my-4 pl-4 border-left">
					<h6 class="text-bl mb-2">Address & Direction:</h6>
					<p>sed quia consequuntur magni dolores eos qui</p>
				</div>
				<p class="para-w3pvt-mobiits-w3layouts">
					<span class="fa fa-map-marker pr-3"></span>25095 Blue Ravine Rd,New Jersey</p>
				<p class="para-w3pvt-mobiits-w3layouts my-sm-3 my-2">
					<span class="fa fa-phone pr-3"></span>032 625 4592</p>
				<p class="para-w3pvt-mobiits-w3layouts">
					<span class="fa fa-envelope-open pr-2"></span>
					<a href="mailto:mail@example.com">info 1@example.com</a>
				</p>
			</div>
			<div class="col-lg-6 regstr-r-w3-w3pvt-mobiits mt-lg-0 mt-5">
				<h4 class="contact-title text-bl mb-4">Get in Touch</h4>
				<div class="form-bg-w3ls">
					<form action="#" method="post">
						<div class="form-group">
							<input type="text" name="Name" class="form-control" placeholder="Name" required="">
						</div>
						<div class="form-group">
							<input type="email" name="Email" class="form-control" placeholder="Email" required="">
						</div>
						<div class="form-group">
							<input type="text" name="Subject" class="form-control" placeholder="Subject" required="">
						</div>
						<div class="form-group">
							<textarea name="Message" class="form-control" placeholder="Message" required=""></textarea>
						</div>
						<button type="submit" class="btn button-w3layouts">Submit</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- //contact -->
<!-- map -->
<div class="map">
	<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1859251.8642025779!2d-76.08274894689792!3d40.06224332601239!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x89c0fb959e00409f%3A0x2cd27b07f83f6d8d!2sNew+Jersey%2C+USA!5e0!3m2!1sen!2sin!4v1474436926209"
	 allowfullscreen></iframe>
</div>



{% endblock %}

templates/galery.html
{% extends "base.html" %}
{% load static %}
 
{% block content %}

<div id="home">
	<!-- banner -->
	<div class="banner_w3lspvt-3">
		<!-- nav -->
		<div class="nav_w3ls pt-4 pb-3 text-center">
			<nav>
				<label for="drop" class="toggle">Menu</label>
				<input type="checkbox" id="drop" />
				<ul class="menu">
					<li><a href="{% url 'yatra:home' %}">Home</a></li>
					<li><a href="index.html">Destination</a></li>
					<li>
						<!-- First Tier Drop Down -->
						<label for="drop-2" class="toggle toogle-2">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
						</label>
						<a href="#">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span></a>
						<input type="checkbox" id="drop-2" />
						<ul class="text-left">
							<li><a href="index.html" class="drop-text">About Us</a></li>
							<li><a href="index.html" class="drop-text">What We Do?</a></li>
							<li><a href="index.html" class="drop-text">Blog</a></li>
							<li><a href="single.html" class="drop-text">Blog Details</a></li>
						</ul>
					</li>
					<li><a href="gallery.html" class="active">Gallery</a></li>
					<li><a href="{% url 'yatra:contact' %}">Contact Us</a></li>
				</ul>
			</nav>
		</div>
		<!-- //nav -->
		<div class="banner-text-2 text-right">
			<div class="banner-bot-2">
				<h1><a href="index.html" class="logo text-wh editContent">Wander</a></h1>
			</div>
		</div>
	</div>
	<!-- //banner -->
</div>

<section class="gallery py-5" id="gallery">
	<div class="container py-md-5">
		<div class="text-center mb-sm-5 mb-4">
			<h3 class="tittle text-bl let mb-2 pt-sm-3">Gallery</h3>
		</div>
		<div class="row news-grids no-gutters text-center">
			<div class="col-md-4 gal-img">
				<a href="#gal1"><img src="{% static 'images/g1.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal2"><img src="{% static 'images/g2.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal3"><img src="{% static 'images/g3.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
		</div>
		<div class="row news-grids no-gutters text-center">
			<div class="col-md-4 gal-img">
				<a href="#gal4"><img src="{% static 'images/g4.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal5"><img src="{% static 'images/g5.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal6"><img src="{% static 'images/g6.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
		</div>
		<div class="row news-grids no-gutters text-center">
			<div class="col-md-4 gal-img">
				<a href="#gal7"><img src="{% static 'images/g7.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal8"><img src="{% static 'images/g8.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
			<div class="col-md-4 gal-img">
				<a href="#gal9"><img src="{% static 'images/g9.jpg' %}" alt="Gallery Image" class="img-fluid"></a>
			</div>
		</div>
		<!-- gallery popups -->
		<!-- popup-->
		<div id="gal1" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g1.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal2" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g2.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal3" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g3.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup3 -->
		<!-- popup-->
		<div id="gal4" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g4.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal5" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g5.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal6" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g6.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal7" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g7.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal8" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g8.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- popup-->
		<div id="gal9" class="pop-overlay animate">
			<div class="popup">
				<img src="{% static 'images/g9.jpg' %}" alt="Popup Image" class="img-fluid" />
				<p class="mt-4">Nulla viverra pharetra se, eget pulvinar neque pharetra ac int. placerat placerat dolor.</p>
				<a class="close" href="#gallery">&times;</a>
			</div>
		</div>
		<!-- //popup -->
		<!-- //gallery popups -->
	</div>
</section>

{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}
{% block banner %}
<!--home-->
		<div class="banner_w3lspvt">
			<!-- nav -->
			<div class="nav_w3ls pt-4 pb-3 text-center">
				<nav>
					<label for="drop" class="toggle">Menu</label>
					<input type="checkbox" id="drop" />
					<ul class="menu">
						<li><a href="{% url 'yatra:home' %}" class="active">Home</a></li>
						<li><a href="#desti">Destination</a></li>
						<li>
							<!-- First Tier Drop Down -->
							<label for="drop-2" class="toggle toogle-2">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span>
							</label>
							<a href="#">Dropdown <span class="fa fa-angle-down" aria-hidden="true"></span></a>
							<input type="checkbox" id="drop-2" />
							<ul class="text-left">
								<li><a href="#about" class="drop-text">About Us</a></li>
								<li><a href="#what" class="drop-text">What We Do?</a></li>
								<li><a href="#blog" class="drop-text">Blog</a></li>
								<li><a href="single.html" class="drop-text">Blog Details</a></li>
							</ul>
						</li>
						<li><a href="{% url 'yatra:galery' %}">Gallery</a></li>
						<li><a href="{% url 'yatra:contact' %}">Contact Us</a></li>
					</ul>
				</nav>
			</div>
			<!-- //nav -->
			<div class="banner-text text-right">
				<div class="banner-bot">
					<h1><a href="index.html" class="logo text-wh">Wander</a></h1>
					<p class="text-bl text-li mt-3 border-bottom pb-4">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut
						odit aut fugit.</p>
					<div class="social-icons mt-4">
						<ul class="list-unstyled">
							<li>
								<a href="#">
									<span class="fa fa-facebook"></span>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="fa fa-twitter"></span>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="fa fa-google-plus"></span>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="fa fa-instagram"></span>
								</a>
							</li>
							<li>
								<a href="#">
									<span class="fa fa-pinterest-p"></span>
								</a>
							</li>
						</ul>
					</div>
					<a href="contact.html" class="btn button-style">Hire Us</a>
				</div>
			</div>
		</div>
<!-- //home -->
{% endblock %}


{% block content %}
<!-- about -->
<section class="about py-5" id="about">
	<div class="container pt-xl-5 pt-lg-3">
		<div class="row about-grids">
			<div class="col-lg-5 about-left">
				<img src="{% static 'images/1.jpg' %}" alt="" class="img-fluid" />
			</div>
			<div class="col-lg-4 about-right mt-lg-0 mt-sm-5 mt-4">
				<h3 class="mb-3 text-bl let">Never Stop Exploring</h3>
				<p class="mb-3">Integer pulvinar leo id viverra feugiat. Pellentesque libero ut justo, semper at tempus vel,
					ultrices in ligula.</p>
				<p>Semper at tempus vel, ultrices in ligula. Integer pulvinar leo id viverra feugiat.</p>
				<a href="single.html" class="btn button-style-3">Learn More</a>
			</div>
			<div class="col-lg-3 about-right p-lg-0 mt-lg-0 mt-sm-5 mt-4">
				<h3 class="mb-3 text-bl let">Our Mission</h3>
				<p class="mb-3">Nulla sollicit udin velit semper at tempus vel, ultrices in ligula leo sed viverra feugiat Nulla
					sollicit udin velit.</p>
				<p>Integer pulvinar leo id viverra feugiat. Pellentesque libero justo, semper at tempus vel.</p>
			</div>
		</div>
	</div>
</section>
<!-- //about -->

<!-- places -->
<section class="trav-grids py-5" id="desti">
	<div class="container py-xl-5 py-lg-3">
		<div class="title-bg text-center py-5 mb-5">
			<h3 class="tittle text-wh let mb-2 pt-lg-3">Place Destination</h3>
			<p class="text-li mx-auto pb-lg-3">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed
				quia consequuntur</p>
		</div>
		<div class="row">
			{% for i in yatra %}
		<div class="col-lg-4 col-sm-6">
		  <div class="box20">
		    <img src="{{ i.images.url }}" alt="" class="img-fluid" />
		    <div class="box-content">
		      <h3 class="title">{{ i.name }} </h3>
		      <span class="post">{{ i.price }}</span>
		    </div>
		  </div>
		</div>
			{% endfor %}
		</div>
		<div class="row pt-lg-3">
			<div class="col-lg-6 mt-4">
				<div class="grids-tem-one">
					<div class="row">
						<div class="col-5 grids-img-left">
							<img src="{% static 'images/tra3.jpg' %}" alt="" class="img-fluid">
						</div>
						<div class="col-7 right-cont">
							<h4 class="mb-3 let tm-clr">Dolor sit amet</h4>
							<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
								aperiamjum.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="col-lg-6 mt-4">
				<div class="grids-tem-one">
					<div class="row">
						<div class="col-5 grids-img-left">
							<img src="{% static 'images/tra4.jpg' %}" alt="" class="img-fluid">
						</div>
						<div class="col-7 right-cont">
							<h4 class="mb-3 let tm-clr">Lorem ipsum dolor</h4>
							<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
								aperiamjum.</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- //places -->

<!-- what -->
<div class="serives-w3pvt-mobi bg-li py-5" id="what">
	<div class="container py-xl-5 py-lg-3">
		<div class="title-bg text-center py-5 mb-5">
			<h3 class="tittle text-wh let mb-2 pt-sm-3">What we do ?</h3>
			<p class="text-li mx-auto pb-sm-3">Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed
				quia consequuntur</p>
		</div>
		<div class="row welcome-bottom pt-4">
			<div class="col-md-4 welcome-grid">
				<span class="fa fa-briefcase"></span>
				<h4 class="my-3">et quasi</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
			<div class="col-md-4 welcome-grid my-md-0 my-4">
				<span class="fa fa-fighter-jet"></span>
				<h4 class="my-3">beatae vita</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
			<div class="col-md-4 welcome-grid">
				<span class="fa fa-globe"></span>
				<h4 class="my-3">sed quian</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
		</div>
		<div class="row welcome-bottom mb-xl-4 mt-md-5 my-md-0 my-4">
			<div class="col-md-4 welcome-grid">
				<span class="fa fa-ship"></span>
				<h4 class="my-3">numqu eiu</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
			<div class="col-md-4 welcome-grid my-md-0 my-4">
				<span class="fa fa-bus"></span>
				<h4 class="my-3">modi tem</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
			<div class="col-md-4 welcome-grid">
				<span class="fa fa-shopping-basket"></span>
				<h4 class="my-3">pora inci</h4>
				<p>Ut enim ad minima veniam, quis nostrum ullam corporis suscipit laboriosam.</p>
			</div>
		</div>
	</div>
</div>
<!-- what -->

<!-- blog -->
<section class="news py-5" id="blog">
	<div class="container py-xl-5 py-lg-5">
		<div class="text-center mb-sm-5 mb-4">
			<h3 class="tittle text-bl let mb-2 pt-sm-3">Our Blog</h3>
		</div>
		<div class="row news-grids text-center">
			<div class="col-md-4 newsgrid">
				<a href="single.html">
					<img src="{% static 'images/g1.jpg' %}" alt="news image" class="img-fluid">
				</a>
				<h4 class="mt-5">Totam Reme</h4>
				<p class="my-4">Nulla pellentesque mi non laoreet eleifend. Integer porttitor mollisar lorem, at molestie arcu
					pulvinar ut. </p>
				<a class="btn button-style-4 mt-4" href="single.html">Learn More</a>
			</div>
			<div class="col-md-4 newsgrid my-md-0 my-5">
				<a href="single.html">
					<img src="{% static 'images/g2.jpg' %}" alt="news image" class="img-fluid">
				</a>
				<h4 class="mt-5">Incidunt ute</h4>
				<p class="my-4">Nulla pellentesque mi non laoreet eleifend. Integer porttitor mollisar lorem, at molestie arcu
					pulvinar ut. </p>
				<a class="btn button-style-4 mt-4" href="single.html">Learn More</a>
			</div>
			<div class="col-md-4 newsgrid">
				<a href="single.html">
					<img src="{% static 'images/g3.jpg' %}" alt="news image" class="img-fluid">
				</a>
				<h4 class="mt-5">Eius Moiora</h4>
				<p class="my-4">Nulla pellentesque mi non laoreet eleifend. Integer porttitor mollisar lorem, at molestie arcu
					pulvinar ut. </p>
				<a class="btn button-style-4 mt-4" href="single.html">Learn More</a>
			</div>
		</div>
	</div>
</section>
<!-- //blog -->

<!-- middle section -->
<section class="w3ls-middle py-5 text-center" id="some">
	<div class="container py-xl-5 my-lg-5">
		<span class="w3-line text-uppercase mb-3">Wander</span>
		<h3 class="w3pvt-web-title mb-4">Start Your Journey</h3>
		<p class="text-botm-mid">Donec consequat sapien ut leo cursus rhoncus. Nullam dui mi, vulputate ac metus at sed ut
			perspiciatis unde omnis iste natus error.</p>
		<a href="#about" class="btn button-style-2 mt-sm-5 mt-4">Read More</a>
	</div>
</section>
	<!-- //middle section -->

{% endblock %}

{% block single %}

	
{% endblock %}